apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: loadbalancer-external
spec:
  type: LoadBalancer
  selector:
    app: amarjot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      